services:
  db:
    image: postgres:16-alpine
    container_name: finance_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: defaultpwd
      POSTGRES_DB: financeapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: finance_backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=financeapp
      - DB_USER=postgres
      - DB_PASSWORD=defaultpwd
      - JWT_SECRET=sua_chave_secreta_aqui_troque_isso_em_producao
      - JWT_EXPIRES_IN=7d
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - db

volumes:
  pgdata: